# Generated by Django 4.2.18 on 2025-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_challenge_assigned_users_challenge_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('broker', 'Corretor')], default='broker', max_length=10),
        ),
    ]
