# Generated by Django 5.1.5 on 2025-01-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
