# Generated by Django 5.1.5 on 2025-01-25 17:43

import django.core.validators
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_user_birth_date_user_cep_user_city_user_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(
                max_length=11,
                unique=True,
                null=True,  # Permite valores nulos temporariamente
                validators=[
                    django.core.validators.RegexValidator(
                        '^\\d{11}$',
                        message='CPF deve conter apenas 11 dígitos.'
                    )
                ],
                verbose_name='CPF',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        '^\\d{5}-\\d{3}$',
                        message='Formato do CEP inválido. Use o formato 12345-678.'
                    )
                ],
                verbose_name='CEP',
            ),
        ),
    ]

