# Generated by Django 5.1.5 on 2025-01-25 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_user_cpf_alter_user_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='CPF deve conter apenas 11 dígitos.')], verbose_name='CPF'),
        ),
    ]
