# Generated by Django 5.1.5 on 2025-01-25 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter exatamente 11 dígitos.', regex='^\\d{11}$')], verbose_name='CPF'),
        ),
    ]
