# Generated by Django 5.1.5 on 2025-01-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_alter_user_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
    ]
